on:
  schedule:
    - cron: '10 08 * * *' # Runs every day at 11:15 AM Irish time

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai==0.27.2 gspread==5.7.2 google==3.0.0 google-api-python-client==2.24.0
      - name: Run script
        env:
          SECRETS: ${{ secrets.SECRETS }}
        run: python app.py
