name: Daily Job

on:
  schedule:
    - cron: '50 12 * * *' # Runs every day at 11:15 AM Irish time

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit==1.18.1 openai==0.27.2 youtube-transcript-api==0.4.1 streamlit-bokeh-events==0.1.2 bokeh==2.4.3 gspread==5.7.2 google==3.0.0
      - name: Run script
        run: python app.py
